### ISSUE TITLE
Register for Julia 1.0?

### ISSUE THREAD

**Issue by cossio** [dfdx/Boltzmann.jl#51]
Why is the package not registered? Does it work on Julia 1.0?
Thanks.

**Comment by dfdx** [comment]
I think when the code here was updated for Julia 1.0 there's was no clear guidance on migrating to new package infrastructure (e.g. adding `Package.toml` instead of `REQUIRE`) so I decided to postpone registration. So far I still don't see clear guidance, but combing both - `Project.toml` and `REQUIRE` - seems to be de facto approach. I'll try to update Boltzmann.jl and register a new version. 

If you need it right now, you can always install the master branch using:

```julia
] add Boltzmann#master
``

**Comment by rofinn** [comment]
Yes, this code was updated, but at the time you could only tag packages through METADATA. Since METADATA is no longer synchronized with the main registry METADATA.jl isn't accepting PRs for 1.0 and we shouldn't need the REQUIRE anymore. The recommended method now is to use [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl) and related tools. If you enable the recommended bot on this repo I can add a Project.toml.

**Comment by dfdx** [comment]
Thanks @rofinn for letting me know about Registrator.jl - I missed the point when we switched to it. I've enabled the bot for Boltzmann.jl, so feel free to add Project.toml. Otherwise, I'll take a look at it myself on the weekend.

**Comment by dfdx** [comment]
@JuliaRegistrator register()

**Comment by dfdx** [comment]
Version `v0.7` is now registered, thanks @rofinn for your help!
